---

#1. Création du repertoire pour l'installation des fichiers WikiJS
- name: "wikijs directory"
  file:
    path: "{{wikijs_directory}}"
    owner: "{{wikijs_user}}"
    group: "{{wikijs_user}}"
    state: directory

#2. Décompresse le fichier source archive Wikijs et le formate sans extension
- name: "uncompress mediawiki archive"
  unarchive:
    src: "{{mediawiki_archive_url}}"
    dest: "{{mediawiki_directory}}"
    owner: "{{wikijs_user}}"
    group: "{{wikijs_user}}"
    remote_src: yes