---

#1. Création du repertoire pour l'installation des fichiers WikiJS
- name: "wikijs directory"
  file:
    path: "{{wikijs_directory}}"
    owner: "{{wikijs_user}}"
    group: "{{wikijs_user}}"
    state: directory

#2. Télécharge le fichier source archive Wikijs
- name: "wikijs download"
  get_url:
    url: "{{wikijs_archive_url}}"
    dest: "{{wikijs_tar_directory}}"

#3. Décompresse le fichier source archive Wikijs tar xzf wiki-js.tar.gz -C ./wiki
- name: "uncompress wiki archive"
  become: true
  unarchive:
    src: "{{wikijs_tar_directory}}{{wikijs_archive_name}}"
    dest: "{{wikijs_directory}}"
    remote_src: true