---

# DNS Wiki JS
wikijs_domain: "b1e3-gr2-wiki-js.westeurope.cloudapp.azure.com"

# User
wikijs_user: "azureuser"

# # Base de données
# mediawiki_db_name: "mediawiki"

# nom du wikijs et son titre
wikijs_name: "wikijs"
wikijs_title: "Wiki JS"

# Répertoire d'installation
wikijs_directory: "/var/www/{{wikijs_name}}"

# Url des sources Mediawiki
wikijs_archive_url: "https://github.com/Requarks/wiki/releases/latest/download/wiki-js.tar.gz"